import * as vscode from "vscode";
import * as dom from "dts-dom";
import { reduce } from "conditional-reduce";
import { DataverseHelper } from "./DataverseHelper";
import { camelize, pascalize } from "../utils/ExtensionMethods";
import { IAttributeDefinition } from "../utils/Interfaces";
import { getWorkspaceFolder, writeFileSync } from "../utils/FileSystem";
import { Placeholders } from "../utils/Placeholders";

const typingNamespace: string = "Xrm";
const typingInterface: string = "EventContext";
const typingMethod: string = "getFormContext";
const typingOmitString = "Omit<Xrm.FormContext, 'getAttribute'>";
const xrmAttribute = "Xrm.Attributes.Attribute";
const toolComment: string = `This code is auto-generated by VSCode Extension 'Dataverse DevTools'
Project Source: https://github.com/Power-Maverick/DataverseDevTools-VSCode

THE CODE AND INFORMATION IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE CODE OR THE USE OR OTHER
DEALINGS IN THE CODE.`;

export class TypingsHelper {
    /**
     * Initialization constructor for VS Code Context
     */
    constructor(private vscontext: vscode.ExtensionContext, private dvHelper: DataverseHelper) {}

    public async generateTyping(entityLogicalName: string): Promise<void> {
        const attributes = await this.dvHelper.getAttributesForEntity(entityLogicalName);
        const camelizedEntityName = camelize(entityLogicalName);
        const pascalizedEntityName = pascalize(entityLogicalName);
        const interfaceAttributes = dom.create.interface(`${pascalizedEntityName}Attributes`);

        let typeEntity = dom.create.alias(pascalizedEntityName, dom.create.namedTypeReference(`${typingOmitString} & ${interfaceAttributes.name}`), dom.DeclarationFlags.None);
        let interfaceEventContext = dom.create.interface(typingInterface);
        interfaceEventContext.members.push(dom.create.method(typingMethod, [], typeEntity));

        const nsXrm = dom.create.namespace(typingNamespace);
        nsXrm.jsDocComment = toolComment;
        nsXrm.members.push(typeEntity);
        nsXrm.members.push(interfaceEventContext);

        attributes
            .sort(this.sortAttributes)
            .filter((a) => a.AttributeType !== "Virtual" && a.IsCustomizable.Value && !a.LogicalName.endsWith("_base"))
            .forEach((a) => {
                interfaceAttributes.members.push(this.createAttributeMethod(a));
                //intf.members.push(dom.create.method("getThing", [dom.create.parameter("x", dom.type.number)], dom.type.void, dom.DeclarationFlags.Optional));
            });

        nsXrm.members.push(interfaceAttributes);
        const refPath = [dom.create.tripleSlashReferencePathDirective("../node_modules/@types/xrm/index.d.ts")];
        const emitOptions: dom.EmitOptions = {
            tripleSlashDirectives: refPath,
        };

        const wsPath = getWorkspaceFolder();
        if (wsPath) {
            let dirsTuple = await vscode.workspace.fs.readDirectory(wsPath);
            let dirs = dirsTuple.filter((d) => d[1] === vscode.FileType.Directory && d[0] !== "node_modules" && !d[0].startsWith(".")).map((d) => d[0]);

            let dirQuickPick: vscode.QuickPickOptions = Placeholders.getQuickPickOptions(Placeholders.typingDirSelection);
            let dirResponse: string | undefined = await vscode.window.showQuickPick(dirs, dirQuickPick);

            if (dirResponse) {
                writeFileSync(vscode.Uri.joinPath(wsPath, dirResponse, `${camelizedEntityName}.d.ts`).fsPath, dom.emit(nsXrm, emitOptions));
                //console.log(dom.emit(nsXrm, emitOptions));
            }
        }
    }

    private createAttributeMethod(attr: IAttributeDefinition): dom.MethodDeclaration {
        let alias = dom.create.alias(xrmAttribute, dom.type.undefined, dom.DeclarationFlags.None);
        return dom.create.method("getAttribute", [dom.create.parameter("name", dom.type.stringLiteral(camelize(attr.LogicalName)))], alias);
        //return dom.create.property(camelize(attr.LogicalName), this.convertType(attr.AttributeType.toLowerCase()), dom.DeclarationFlags.Optional);
    }

    private sortAttributes(a1: IAttributeDefinition, a2: IAttributeDefinition) {
        if (a1.LogicalName > a2.LogicalName) {
            return 1;
        }
        if (a1.LogicalName < a2.LogicalName) {
            return -1;
        }
        return 0;
    }

    private convertType(t: string): dom.Type {
        return reduce<dom.Type>(
            t,
            {
                string: () => dom.type.string,
                integer: () => dom.type.number,
                double: () => dom.type.number,
                uniqueidentifier: () => dom.type.string,
                memo: () => dom.type.string,
                money: () => dom.type.number,
                boolean: () => dom.type.boolean,
                bigint: () => dom.type.number,
                decimal: () => dom.type.number,
                datetime: () => dom.type.string,
            },
            () => dom.type.object,
        );
    }
}
